services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: