services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENV: local
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    command: >
      ./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        ENV: local
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
